print("Corona Circular")
print("=================")
radio_ma = float(input("Ingrese radio mayor: "))
radio_me = float(input("Ingrese radio menor: "))
area = 3.14*(radio_ma**2 - radio_me**2)
perimetro = 2*3.14*(radio_me + radio_ma)
print("")
print("Resultados")
print("Area: " , area.__round__(2))
print("Area: " , perimetro.__round__(2))